[package]
name = "vidsquash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsmpeg = { version = "0.14.2+ffmpeg.6.1" }
img_hash = "1"
